### ISSUE TITLE
getting Error-**Error in FUN(newX[, i], ...) : argument "x2" is missing, with no default**

### ISSUE THREAD

**Issue by mlnjsh** [ArdiaD/DEoptim#1] opened 2017-06-01 03:44 UTC
I fave following function to maximize , I run the following code 

```r
f<-function(x1,x2,x3){
  -53.06453125+5.146767857*x1+0.001306786*x2+0.25028125*x3-0.00019125*x1*x2- 
    0.00005594*x2*x3-0.111714286*x1^2+0.00000032*x2^2
}
###############################################################
lower<-c(18,4000,5)
upper<-c(20,4800,13)
set.seed(100)

library(DEoptim)
set.seed(1234)
DEoptim(f, lower, upper)
##############################################################
```
getting an ERROR

> **Error in FUN(newX[, i], ...) : argument "x2" is missing, with no default**

**Comment by joshuaulrich** [comment] 2017-06-01 04:02
The vector of parameters to optimize all need to be passed via the first
argument of the objective function.

f <- function (x) {
  x1 <- x[1]
  x2 <- x[2]
  x3 <- x[3]
  -53.06453125 + 5.146767857 * x1 +
  0.001306786 * x2 + 0.25028125 * x3
  - 0.00019125 * x1 * x2 - 0.00005594 * x2 * x3
  - 0.111714286 * x1^2 + 0.00000032 * x2^2
}
DEoptim(f, lower, upper)

**Comment by joshuaulrich** [comment] 2017-06-01 17:08
Closing, since this is not a bug in the package.

**Closed as completed by joshuaulrich** 2017-06-01 17:08 UTC
