### ISSUE TITLE
Stack Imbalance

### ISSUE THREAD

**Issue by johncancian** [ArdiaD/DEoptim#18] opened 2022-08-04 12:53 UTC
Hello,

When I use the VTR control I consistently see the following warning:

Warning: stack imbalance in '=', 66 then 65
Warning: stack imbalance in '{', 62 then 61
Warning: stack imbalance in 'if', 60 then 59

It is a warning, but should I be concerned?

**Comment by joshuaulrich** [comment] 2022-08-04 15:45
That's a problem in the C code that we should fix. Can you provide a reproducible example based on one of the minimal examples in the package?

**Comment by johncancian** [comment] 2022-10-18 19:13
Hey Joshua, I have an example of DEoptim that shows the stack imbalance issue when I use VTR. It actually goes to an error. When I use itermax the process runs to completion. How do I send you my scripts and data?

**Comment by joshuaulrich** [comment] 2022-10-18 19:23
> How do I send you my scripts and data?

[Email them to me](https://github.com/joshuaulrich/xts/blob/master/DESCRIPTION#L7).

**Comment by johncancian** [comment] 2022-10-20 18:33
Hey Joshua, I sent you some files yesterday. Just want to confirm you got them.

**Comment by joshuaulrich** [comment] 2022-10-20 18:39
I did get them. Thanks!

**Comment by joshuaulrich** [comment] 2022-10-25 19:16
I was able to replicate the issue. Here's the output from `DEoptim()`. The issue likely stems from there being only 2 function evaluations (`nfeval`) and 0 iterations. I start the debugger right after the `DEoptim()` call finishes.

```r
Warning: stack imbalance in '=', 12 then 11
Called from: dothing(things[i, ])
Browse[1]$ output
$optim
$optim$bestmem
              par1               par2               par3               par4               par5               par6               par7
11.632294707931578 -0.903391908970661  0.000000000000000  6.818841162836179  0.000000000000000  1.071092676394619  0.466343999004457

$optim$bestval
[1] 0.00179344306408802

$optim$nfeval
[1] 2

$optim$iter
[1] 0


$member
$member$lower
 par1  par2  par3  par4  par5  par6  par7 
 2.00 -0.99  0.00  0.50  0.00  0.10  0.01 

$member$upper
par1 par2 par3 par4 par5 par6 par7 
20.0 -0.7  0.0  7.0  0.0  2.0  2.0 

$member$bestmemit
                   par1                  par2                  par3                 par4                  par5                  par6                  par7
1 1.69425184945613e-315 1.69425240280966e-315 1.69425295616318e-315 1.6942535095167e-315 1.69425406287023e-315 1.69425461622375e-315 1.69425516957727e-315

$member$bestvalit
  [1] 1.96294613082576e-316 1.96293783052291e-316 1.96286036102964e-316 1.96285206072679e-316 1.96292953022006e-316 1.96277182446590e-316 1.96284376042394e-316
  [8] 1.96283546012109e-316 1.96282715981824e-316 1.96281885951539e-316 1.96292122991721e-316 2.98448732723758e-316 3.35832861982989e-316 2.98448456046997e-316
 [15] 1.96012956139194e-316 2.56607380359258e-316 1.96291292961436e-316 1.96274692355735e-316 2.56623506661939e-316 2.58970990408963e-316 2.98448179370235e-316
 [22] 2.58971939015003e-316 2.58972887621043e-316 1.96281055921254e-316 1.96011691331141e-316 1.96278565830399e-316 2.58973836227083e-316 1.96273032295165e-316
 [29] 1.96272755618404e-316 1.96272478941642e-316 1.96274415678974e-316 2.58974784833123e-316 2.58975733439163e-316 2.58976682045203e-316 2.98447902693473e-316
 [36] 2.98447626016712e-316 2.58977630651243e-316 2.98447349339950e-316 2.98447072663188e-316 3.33866204035779e-316 2.56633625126365e-316 2.56634257530392e-316
 [43] 1.96274139002212e-316 1.96272202264880e-316 1.96271925588119e-316 1.96273862325450e-316 1.96269712174025e-316 1.96271648911357e-316 1.96271372234595e-316
 [50] 2.58978263055270e-316 1.96271095557834e-316 1.96270542204310e-316 1.96273585648689e-316 1.96010426523088e-316 2.56608012763285e-316 2.58978895459296e-316
 [57] 2.58979527863323e-316 1.96273308971927e-316 1.96270265527549e-316 2.98446795986427e-316 1.96009794119061e-316 1.96269988850787e-316 2.58979844065336e-316
 [64] 2.58980792671376e-316 2.58981425075403e-316 2.91565449671150e-316 3.33865887833766e-316 2.58982057479430e-316 2.31770977019580e-316 2.56624139065965e-316
 [71] 2.98446519309665e-316 2.58982689883456e-316 2.98446242632903e-316 2.58983322287483e-316 2.58983954691510e-316 2.58984587095536e-316 2.98445965956142e-316
 [78] 2.58985219499563e-316 2.58985851903590e-316 2.58986484307616e-316 2.98445689279380e-316 2.58987116711643e-316 2.58988065317683e-316 2.98445135925857e-316
 [85] 2.58988697721710e-316 2.58989330125736e-316 2.98444859249095e-316 2.98445412602618e-316 2.98444582572333e-316 2.98444305895572e-316 2.58989962529763e-316
 [92] 2.98444029218810e-316 2.58990594933790e-316 2.58991227337816e-316 3.34079442768524e-316 2.58991859741843e-316 2.62140559865415e-316 2.98443752542048e-316
 [99] 2.98443475865287e-316 2.58992492145870e-316 2.56628565894152e-316 2.56634889934419e-316 2.56629198298179e-316 2.58993124549897e-316 2.56629830702205e-316
[106] 2.98443199188525e-316 2.98442922511763e-316 2.98439602390623e-316 2.56598526702885e-316 3.35832585306227e-316 2.56635522338445e-316 2.98442645835002e-316
[113] 2.56599159106911e-316 2.03767612890060e-316 2.56599791510938e-316 2.98442369158240e-316 2.56600423914965e-316 2.98442092481478e-316 1.95989873392221e-316
[120] 2.98441815804717e-316 2.56601056318992e-316 2.56601688723018e-316 2.98441539127955e-316 3.35832308629466e-316 2.56636154742472e-316 2.56630463106232e-316
[127] 2.98441262451193e-316 2.56624771469992e-316 2.56602321127045e-316 2.98440985774432e-316 3.35832031952704e-316 2.56603585935098e-316 2.21974564343337e-316
[134] 2.98440709097670e-316 2.56625403874019e-316 2.98440432420908e-316 2.56604218339125e-316 2.56604850743152e-316 2.98440155744147e-316 2.45550625983100e-321
[141] 6.56874426186034e-316 1.66324385474537e-315 6.91177402359656e-310 6.91177402358075e-310 6.91177402347324e-310 6.91177402357126e-310 6.91177402341000e-310
[148] 6.91177402346059e-310 6.91177402352067e-310 6.91177402353648e-310 6.91177402349221e-310 6.91177402351751e-310 6.91177402349537e-310 6.91177402359340e-310
[155] 6.91177402357442e-310 6.91177402358391e-310 6.91177402351118e-310 6.91177402356178e-310 6.91177402343846e-310 6.91177402352383e-310 6.91177402356494e-310
[162] 6.91177402345743e-310 6.91177402354280e-310 6.91177402348905e-310 6.91177402350170e-310 6.91177402344162e-310 6.91177402357759e-310 6.91177402347640e-310
[169] 6.91177402340367e-310 6.91177402354913e-310 6.91177402343213e-310 6.91177402342897e-310 6.91177402359972e-310 6.91177402347956e-310 6.91177402348589e-310
[176] 6.91177402354597e-310 6.91177402355545e-310 6.91177402344478e-310 6.91177402356810e-310 6.91177402343529e-310 6.91177402346375e-310 6.91177402359023e-310
[183] 6.91177402350486e-310 6.91177402341948e-310 6.91177402341632e-310 6.91177217741632e-310 6.91177217742581e-310 5.58294179800609e-322 2.58789055675538e-316
[190] 6.91178178118055e-310 6.91177217742264e-310 6.91177217743845e-310 6.91177217751118e-310 3.21142669796810e-322 7.29129115849965e-316 1.70738660441345e-315
[197] 1.68944103344945e-315 3.79442416006077e-321  0.00000000000000e+00  0.00000000000000e+00

$member$pop
                   [,1]               [,2] [,3]              [,4] [,5]              [,6]               [,7]
 [1,]  7.11435660114512 -0.821457939639222    0 4.227830457966775    0 0.210493134334683 0.0824329102295451
 [2,] 18.77332604350522 -0.796579458625056    0 2.007087926263921    0 1.155107956286520 1.5735600235639140
 [3,] 15.78547384636477 -0.846718057009857    0 4.823423362919129    0 1.725336074898951 0.7511489568604156
 [4,] 19.45012703118846 -0.712956615013536    0 5.489945847657509    0 1.303698895173147 1.2447898837993854
 [5,]  7.67541914246976 -0.989387531676330    0 4.506410127039999    0 0.517029028851539 0.7332680354826152
 [6,]  9.58758402476087 -0.908960356088355    0 4.684513194835745    0 1.558059460320510 0.3913338477187790
 [7,]  4.31814752565697 -0.751637871719431    0 1.329808039707132    0 1.565228063170798 1.1827005849080161
 [8,] 15.59999190550297 -0.987440375015140    0 1.761129558435641    0 1.363704983540811 1.8538300885562784
 [9,]  9.67056728433818 -0.840805418121163    0 6.585809674230404    0 1.136886556982063 1.7333043876080774
[10,]  2.67647281521931 -0.914039407700766    0 5.924408370396122    0 1.055016602668911 1.0475469511607662
[11,] 19.70194467809051 -0.721297234899830    0 6.455938947154209    0 1.233051351318136 0.8659270645375363
[12,] 19.70137157803401 -0.958673198213801    0 0.603909667115659    0 1.630277473852038 1.3296549431816675
[13,] 10.55142217595130 -0.865304009746760    0 2.061935772188008    0 0.380319046322256 0.4185827758535743
[14,]  7.95211721165106 -0.888802755053621    0 0.593475333647802    0 1.151297369995155 1.4923964433325454
[15,]  2.68582696467638 -0.827992639611475    0 2.903199816937558    0 1.431387494434603 1.6450103504909201
[16,] 13.31525003165007 -0.976358205378056    0 0.657953437999822    0 0.818926723068580 0.2215284679247998
[17,]  7.52534171100706 -0.902448343741707    0 6.492261117789894    0 1.633964250865392 0.1863815375347622
[18,]  5.23064584936947 -0.979927019681782    0 5.500772475381382    0 1.976727073593065 0.8910055927233771
[19,] 17.43034827290103 -0.814497263829689    0 2.507503430475481    0 0.928895791387185 1.5127619373169727
[20,] 19.02982567064464 -0.927002239564899    0 3.485315366415307    0 0.177453741617501 0.2700815099966712
[21,]  5.91939319064841 -0.821564875910990    0 6.497893247986212    0 0.236700891656801 1.3995195500482804
[22,]  6.94050816772506 -0.904903193190694    0 4.802552335080691    0 1.426421473291703 0.5351507745124400
[23,]  8.47215868113562 -0.871925503564998    0 6.998023163178004    0 0.891565662133507 1.8825314854294992
[24,]  6.13984028669074 -0.815472414856777    0 6.752652103197761    0 1.235333222686313 1.1678856657445431
[25,] 18.10734984371811 -0.778524989592843    0 4.865986831136979    0 0.553766665025614 1.2946770880930125
[26,]  5.27004965813830 -0.862122167772613    0 1.106806517927907    0 1.885192177444696 1.4393600189778955
[27,]  6.82210724754259 -0.890994838059414    0 2.570468718302436    0 1.319090496096760 0.3148341003595851
[28,] 11.63229470793158 -0.903391908970661    0 6.818841162836179    0 1.071092676394619 0.4663439990044572
[29,] 16.65248432336375 -0.892353957074229    0 4.204802657710388    0 1.032560772728175 1.2812700349185615
[30,] 16.80438670469448 -0.798998992624693    0 6.935325987637043    0 0.922945165494457 1.6377683758432977
[31,] 16.38373368978500 -0.846089387251995    0 2.958230083459057    0 1.177895017364062 1.7436978776683099
[32,]  8.74928384600207 -0.773348386976868    0 5.495898417429999    0 1.281487123970874 1.3073216920974664
[33,]  7.05920739145949 -0.903956753124949    0 1.760887649143115    0 0.496210403554141 1.0832024168339558
[34,] 11.82835442200303 -0.968098808054347    0 1.645798078505322    0 0.948888168740086 0.2169316997216083
[35,]  4.32342512812465 -0.736880515576340    0 4.911518816719763    0 0.662432714481838 1.8635056450893170
[36,] 13.00962881417945 -0.915356884559151    0 4.381790046114475    0 0.184385185502470 1.0642444089055061
[37,] 14.47234161058441 -0.972084808461368    0 3.663873069919646    0 1.393934870208614 0.3302488652267493
[38,]  4.46253549726680 -0.864220116466749    0 4.245033277082257    0 1.515670942235738 1.3046121504786425
[39,] 14.15561254415661 -0.706746021171566    0 2.475998715148307    0 0.198050951305777 0.8449030706007034
[40,]  2.30425593117252 -0.952961789527908    0 3.256264866795391    0 1.083883032319136 1.8547402904438786
[41,]  2.52375635830685 -0.815716275384184    0 4.241346167516895    0 1.092896048887633 1.4603245709999464
[42,]  9.26555145159364 -0.751110070266295    0 0.803201903472655    0 1.850305314175785 0.1119170826906338
[43,] 12.09578538360074 -0.882715206076391    0 1.558394491788931    0 0.715377801423892 1.8186784090031869
[44,]  3.17805365007371 -0.799372209329158    0 5.405099963070825    0 1.262382469652221 1.3043573015858418
[45,] 10.91313465777785 -0.754704782611225    0 2.893240926903673    0 0.798293867870234 0.5563937331293710
[46,]  5.07783005014062 -0.777302477755584    0 6.274536293814890    0 0.231276833871379 0.1411253968882374
[47,]  4.37731907237321 -0.730134093263186    0 2.140632696216926    0 1.691317564691417 1.0297183864098043
[48,] 10.68742145923898 -0.810700231089722    0 6.017285292386077    0 1.729995280643925 0.8162150835106149
[49,] 11.44160575699061 -0.939824055070058    0 5.204460766632110    0 1.561913648294285 1.9614733895775862
[50,]  9.43142979731783 -0.879034465369768    0 3.907085426384583    0 0.292437505512498 1.1086441285768525
[51,] 15.68951285257936 -0.775750204441138    0 2.015308052301407    0 0.916586009063758 0.0550187936937436
[52,] 18.51693016337231 -0.862253676042892    0 4.529626076109707    0 0.664497440075502 1.8786618293798529
[53,] 11.06145944166929 -0.985250432894100    0 4.130784567678347    0 1.523498263512738 1.5334394610440358
[54,]  6.76474998891354 -0.901034598033875    0 4.508240436553024    0 1.366893551545218 0.6688714736397379
[55,] 14.20215524500236 -0.740657051270828    0 2.294832503190264    0 0.620562434522435 0.0197923780675046
[56,]  4.61071639321744 -0.718826116563287    0 5.337097643874586    0 1.043048957432620 0.4285643939371221
[57,] 15.77445259084925 -0.799166068467312    0 4.655456858221442    0 0.892147993785329 1.0108148256666027
[58,]  5.83204000070691 -0.740627750447020    0 4.540149930166081    0 0.434888000204228 0.3601481205620803
[59,]  2.96306883916259 -0.968241957195569    0 6.039246681961231    0 1.885254220105708 1.3953016181802378
[60,]  6.04980278387666 -0.974681778438389    0 6.640873117488809    0 0.647342862840742 0.6979170995811000
[61,]  7.42714439192787 -0.834578008877579    0 5.774652312044054    0 0.400080305384472 1.6334148945217022
[62,]  7.61889732489362 -0.745989828752354    0 5.664481108658947    0 0.182972144079395 1.5307371636363678
[63,] 17.40472128707916 -0.779226445448585    0 6.974409282440320    0 0.394519912824035 0.4476208934839815
[64,]  4.80294842319563 -0.881722620278597    0 4.718216269277036    0 0.432004563463852 0.1048095501307398
[65,] 13.77030293038115 -0.716769961407408    0 2.638686842168681    0 1.710572224156931 1.8021227010339498
[66,]  5.37986947502941 -0.944404864388052    0 6.767048547510058    0 0.304463489376940 0.0806956112477928
[67,] 19.43263810221106 -0.988811052795500    0 1.180773526197299    0 1.249928145995364 1.5451956875342876
[68,] 14.32324093487114 -0.756234129748773    0 6.902220663498156    0 0.655050161597319 0.3246693237544969
[69,]  5.30528294621035 -0.898161421446130    0 4.980524802580476    0 0.526502142217942 0.1870293632219546
[70,]  4.82871901616454 -0.915330935944803    0 2.368020434747450    0 1.693248266493902 1.5914304481330328

$member$storepop
list()


attr(,"class")
[1] "DEoptim"
```

**Comment by johncancian** [comment] 2022-10-25 19:36
Thank you Joshua. Is there anything else I can provide you with to help?

Regards,
John

**Comment by joshuaulrich** [comment] 2022-10-25 20:46
This looks like a regression to me. These were fixed in a prior development version.

**Comment by joshuaulrich** [comment] 2022-10-25 21:12
@johncancian I just pushed a commit that appears to fix these issues. It looks like there are other regressions too, but I haven't looked closely into them.

You can install this branch using the command below. Note that you'll need to have Rtools (or the linux/macOS equivalent) in order to install.

```
remotes::install_github("ArdiaD/DEoptim@18-cran-regressions")
```

**Comment by k-m-m** [comment] 2022-10-26 07:46
This branch passes R CMD check --as-cran DEoptim_2.2-6.tar.gz  using R Under development (unstable) (2022-10-16 r83107).

**Comment by k-m-m** [comment] 2022-10-28 02:36
reverted to changes in c231be6

**Comment by joshuaulrich** [comment] 2022-10-28 15:43
A couple lines were missed. I will fix.

**Closed as completed** 2022-10-28 15:47 UTC
Labels: bug
